### ISSUE TITLE
[Bug]: Multiple rendering bugs

### ISSUE THREAD

**Issue by IVsniper** [Team-Immersive-Intelligence/ImmersiveIntelligence#271]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧊Rendering

### Description

Multiple rendering bugs, including:
- Missing ropes in skycart/skycrate
- Missing texture of fluid inserter in hands and inventry (In world it does exist)
- Heavy chemthrower projectiles are super-white
- Missing paker gui (resulted crash)
- Error in the manual (resulted crash)

### Side

Client

### Reproduction

Chemthrower:
1. Build Chemthrower
2. Make it target anything
3. Projectiles are existing, but are white (also not dealing damage (#264))
Skycart/Skycrate:
1. Build Skycart/Skycrate
2. Try to connect post(S) with station
3. Rope isn't here
Packer:
1. Build packer
2. Open it
3. Game crashes refferencing in the error packer's gui
Manual:
1. Open IE manual
2. Open Warfare --> Casing pouch
3. Game crashes with (Error: java.lang.IllegalAccessError: tried to access field net.minecraft.nbt.NBTTagList.field_74747_a from class pl.pabilo8.immersiveintelligence.common.util.easynbt.EasyNBT)

### Expected Behaviour

Everything to work fine and no crashes ^^

### Logs

https://mclo.gs/qubnMqO / https://mclo.gs/PgYYXPt <-- Everything up to packer || Manual crash --> https://mclo.gs/JNj4O8h / https://mclo.gs/kCXcGal

### Other Evidence

![image](https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/assets/45400200/0f96a1b9-abfe-4c38-ae11-2bdf9976a3f1)
![image2](https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/assets/45400200/64b57119-2e21-4b98-b9aa-33d97f9ac8b9)

### Operating System

Windows 10 or newer

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.0 (Recent Dev Build)

### Immersive Engineering Version

0.98

**Comment by IVsniper** [comment]
Update:
- A lot more of manual pages are causing easynbt crash
- Scanning conveyor textures are bugged
![image](https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/assets/45400200/3cd08c77-40c1-4252-ade5-a4a741eb008f)
- Redstone-Data interface texture is misplaced
![image2](https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/assets/45400200/0c8230bf-8702-4936-aabc-dcff8819d1ee)
- Sawmill blade texture is missing (all blades) (not critical)
![image3](https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/assets/45400200/0b507f5f-0d94-4deb-94ea-76064d85b8f6)
- Coagulator fluids textures are bugged (not critical)
![image4](https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/assets/45400200/9396e08c-d7ef-462e-b63a-efbcbbddc458)
- Arithmetic-logic machines also lack some textures for circuit boards (not critical)
![image5](https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/assets/45400200/aeeb640c-5922-40f2-9513-c7f22363c920)
Full list:
- Type conversion circuit
- Cryptograpgher circuit
- Map orientation circuits
- Fluidstack operations circuit
- Vector arithmetic circuit
- Logic circuit
- Text processor circuit
- Array operations circuit
- Arithmetic circuit
- Comparator circuit

**Comment by LeKripiY** [comment]
Update :

- Electrolyzer model and hammering block are wrong
![image](https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/assets/77859121/ed4dd058-e4d4-4398-910a-af39fab2f030)

**Comment by IVsniper** [comment]
Thank you for adding this, i wasn't able to add Electrolyzer to the issue since i couldn't form it, thought it was disabled (like vehicle workshop). And about Aluminium Chain Fence, i don't really know what you're talking about, if you don't mind, could you explain me about it in the discord. Thank you again

**Comment by IVsniper** [comment]
Latest build update:
Every issue except the scanning conveyor is still active. Scanning conveyor got new model, but it still is misplaced:
![image](https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/assets/45400200/b05fe8d9-4951-4219-8e9e-11c25c69f8b9)
Also precision assembles is missing animations:
https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/assets/45400200/e3f2e264-9cf0-4491-a04e-56abb33fb96d

**Comment by Pabilo8** [comment]
Electrolyzer should be fixed in current dev build already, please re-check if you can form it.
Casing pouch's GUI should work too, please check it as well.
Scanning conveyor's rotation will be fixed soon.

**Comment by Pabilo8** [comment]
Also please check the aluminium fence gate, it works fine in-dev, but not sure about normal game.

**Comment by IVsniper** [comment]
Ah yes, sorry.
- The electrolyzer is ok now.
- Casing pouch gui is ok (manual is crsahing when opening 2nd page of it) (Error: java.lang.NullPointerException: Updating screen events) (https://mclo.gs/xbIO5bd)
- Packer gui is still broken. (crashes)
- Chain fence gate not fixed

**Comment by IVsniper** [comment]
As of "Curseforge 0.3.0" build:
- Packer was fixed
- Redstone-data Interface was fixed
- Electrolyzer was fixed
- Scanning conveyor was fixed
- Fluid inserter was fixed
- Sawmill was fixed

**Comment by IVsniper** [comment]
As of "Curseforge 0.3.0" build:
Still present issues:
- Chemthrower projectiles are white (https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/issues/264)
- Skycart/Skycrate ropes missing
- Coagulator fluids textures
- Arithmetic-logic machines circuit boards missing textures

**Comment by LeKripiY** [comment]
Hello, Everything said by IVsniper is true, although I can't seem to get the coagulator working so I can't test it.
And the Aluminum chain fence gate is still missing one block activation, to clarify, if you have immersive petroleum installed, when you place it using the projector [Without rotating, so initial rotation] it is the block on the back right side:
![image](https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/assets/77859121/5c4b666b-d4ec-4025-94bd-0a71fb926b9d)

**Comment by IVsniper** [comment]
Thx for telling. Most likely i'll make a 2.0 version of this post, because this one is messy rn

**Comment by Pabilo8** [comment]
Closed, most of it is fixed, but things related to Skycrates will be handled in another release.
